'use strict';
const KEY='mahjong-record-v2';
const $=id=>document.getElementById(id);
const today=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const id=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize=x=>{if(!x||!Array.isArray(x.shops)||!Array.isArray(x.records))throw Error('データ形式が違います');return {shops:x.shops.map(s=>({id:String(s.id),name:String(s.name)})),records:x.records.map(r=>({id:String(r.id),shop:String(r.shop),date:String(r.date),counts:Array.isArray(r.counts)?r.counts.map(Number):[],pt:Number(r.pt)})).filter(r=>r.counts.length===4&&r.counts.every(n=>Number.isInteger(n)&&n>=0)&&Number.isFinite(r.pt)&&/^\d{4}-\d{2}-\d{2}$/.test(r.date))}};
let state={shops:[],records:[]},counts=[0,0,0,0],editing=null;
try{const raw=localStorage.getItem(KEY);if(raw)state=normalize(JSON.parse(raw))}catch(e){alert('保存データを読み込めませんでした。上書きせず、バックアップの復元を試してください。');}
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch(e){alert('端末への保存に失敗しました。空き容量やブラウザ設定を確認してください。');return false}};
const change=next=>{const old=state;state=next;if(!save()){state=old;return false}render();return true};
$('date').value=today();$('date').max=today();
$('addShop').onclick=()=>{const name=$('shopName').value.trim();if(!name)return alert('店舗名を入力してください');if(state.shops.some(s=>s.name===name))return alert('登録済みの店舗です');if(change({...state,shops:[...state.shops,{id:id(),name}]})){$('shopName').value='';$('entryShop').value=state.shops.at(-1).id}};
const setCounts=()=>{$('counters').innerHTML=counts.map((v,i)=>`<div class="counter"><strong>${i+1}着</strong><div class="right"><button class="secondary" data-rank="${i}" data-step="-1" aria-label="${i+1}着を減らす">－</button><span class="count">${v}</span><button data-rank="${i}" data-step="1" aria-label="${i+1}着を増やす">＋</button></div></div>`).join('');$('gameTotal').textContent=counts.reduce((a,b)=>a+b,0)};
$('counters').onclick=e=>{const b=e.target.closest('button[data-rank]');if(!b)return;const i=Number(b.dataset.rank);counts[i]=Math.max(0,counts[i]+Number(b.dataset.step));setCounts()};
const validDate=s=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const d=new Date(s+'T12:00:00');return !Number.isNaN(d.getTime())&&today()>=s&&`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`===s};
$('saveRecord').onclick=()=>{const shop=$('entryShop').value,date=$('date').value,pt=Number($('points').value);if(!state.shops.some(s=>s.id===shop))return alert('店舗を選択してください');if(!validDate(date))return alert('日付を確認してください');if(!counts.some(Boolean))return alert('着順を入力してください');if($('points').value.trim()===''||!Number.isFinite(pt))return alert('ポイントを確認してください');const r={id:editing||id(),shop,date,counts:[...counts],pt};const records=editing?state.records.map(x=>x.id===editing?r:x):[...state.records,r];if(change({...state,records})){editing=null;counts=[0,0,0,0];$('points').value='0';$('saveRecord').textContent='記録を保存';$('cancelEdit').classList.add('hidden');setCounts();alert('保存しました')}};
$('cancelEdit').onclick=()=>{editing=null;counts=[0,0,0,0];$('points').value='0';$('saveRecord').textContent='記録を保存';$('cancelEdit').classList.add('hidden');setCounts()};
$('history').onclick=e=>{const b=e.target.closest('button[data-id]');if(!b)return;const r=state.records.find(x=>x.id===b.dataset.id);if(!r)return;if(b.dataset.action==='delete'){if(confirm('この記録を削除しますか？'))change({...state,records:state.records.filter(x=>x.id!==r.id)});return}editing=r.id;counts=[...r.counts];$('entryShop').value=r.shop;$('date').value=r.date;$('points').value=r.pt;$('saveRecord').textContent='変更を保存';$('cancelEdit').classList.remove('hidden');setCounts();window.scrollTo({top:$('counters').getBoundingClientRect().top+window.scrollY-200,behavior:'smooth'})};
['filterShop','period','chartType'].forEach(x=>$(x).addEventListener('change',render));
const summary=rs=>{const c=[0,0,0,0];let pt=0;rs.forEach(r=>{r.counts.forEach((v,i)=>c[i]+=v);pt+=r.pt});const games=c.reduce((a,b)=>a+b,0),rate=n=>games?(n/games*100).toFixed(1)+'%':'0%';return {c,pt,games,rate,avg:games?(c.reduce((s,v,i)=>s+v*(i+1),0)/games).toFixed(2):'—'}};
function render(){const oldEntry=$('entryShop').value,oldFilter=$('filterShop').value;const options=state.shops.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');$('entryShop').innerHTML=options;$('filterShop').innerHTML='<option value="all">全店舗</option>'+options;if(state.shops.some(s=>s.id===oldEntry))$('entryShop').value=oldEntry;if(oldFilter==='all'||state.shops.some(s=>s.id===oldFilter))$('filterShop').value=oldFilter;$('shopsList').textContent=state.shops.length?`登録店舗：${state.shops.map(s=>s.name).join('、')}`:'店舗を追加してください';const f=$('filterShop').value,p=$('period').value,now=today();const rs=state.records.filter(r=>(f==='all'||r.shop===f)&&(p==='all'||p==='today'&&r.date===now||p==='month'&&r.date.slice(0,7)===now.slice(0,7)));const s=summary(rs);const vals=[['総対局数',s.games+' G'],['トップ率',s.rate(s.c[0])],['平均順位',s.avg],['連対率',s.rate(s.c[0]+s.c[1])],['ラス率',s.rate(s.c[3])],['合計ポイント',(s.pt>0?'+':'')+Number(s.pt.toFixed(2))+' pt']];$('stats').innerHTML=vals.map(([l,v])=>`<div class="stat"><div class="muted small">${l}</div><div class="value">${v}</div></div>`).join('');$('rankBars').innerHTML=s.c.map((v,i)=>`<div class="barline"><div class="small">${i+1}着 ${v}回（${s.rate(v)}）</div><div class="bartrack"><div class="barfill" style="width:${s.games?v/s.games*100:0}%"></div></div></div>`).join('');$('history').innerHTML=rs.length?rs.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(r=>`<div class="historyRow"><div><strong>${esc(r.date)}　${esc(state.shops.find(s=>s.id===r.shop)?.name||'不明')}</strong><div class="small muted">${r.counts.map((v,i)=>`${i+1}着:${v}`).join(' / ')}</div><div>${r.pt>0?'+':''}${r.pt} pt</div></div><div class="actions"><button class="secondary" data-action="edit" data-id="${esc(r.id)}">編集</button><button class="danger" data-action="delete" data-id="${esc(r.id)}">削除</button></div></div>`).join(''):'<p class="muted">記録がありません</p>';drawChart(rs)}
function drawChart(rs){const type=$('chartType').value,groups=new Map();rs.forEach(r=>{const k=type==='yearly'?r.date.slice(0,4):r.date.slice(0,7);groups.set(k,(groups.get(k)||0)+(type==='monthlyGames'?r.counts.reduce((a,b)=>a+b,0):r.pt))});const rows=[...groups].sort((a,b)=>a[0].localeCompare(b[0])).slice(-24);if(!rows.length){$('chart').innerHTML='<p class="muted">記録を登録するとグラフが表示されます</p>';return}const W=600,H=250,P=42,vals=rows.map(x=>x[1]),min=Math.min(0,...vals),max=Math.max(0,...vals),span=max-min||1,x=i=>P+(W-P*2)*(rows.length===1?.5:i/(rows.length-1)),y=v=>H-P-(v-min)/span*(H-P*2);const line=rows.map(([k,v],i)=>`${i?'L':'M'}${x(i)},${y(v)}`).join(' ');$('chart').innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="成績グラフ"><line x1="${P}" x2="${W-P}" y1="${y(0)}" y2="${y(0)}" stroke="#96b5a9" stroke-dasharray="4 4"/><path d="${line}" fill="none" stroke="#62d7a1" stroke-width="3"/>${rows.map(([k,v],i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="4" fill="#62d7a1"><title>${esc(k)}: ${Number(v.toFixed(2))}</title></circle>${i===0||i===rows.length-1||rows.length<=7?`<text x="${x(i)}" y="${H-12}" text-anchor="middle" font-size="11" fill="#d8e9e2">${esc(k.slice(type==='yearly'?0:5))}</text>`:''}`).join('')}<text x="8" y="${P}" fill="#d8e9e2" font-size="12">${Number(max.toFixed(1))}</text><text x="8" y="${H-P}" fill="#d8e9e2" font-size="12">${Number(min.toFixed(1))}</text></svg>`}
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`mahjong-backup-${today()}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('import').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const data=normalize(JSON.parse(await file.text()));if(!confirm('現在のデータをバックアップの内容で置き換えます。続行しますか？'))return;if(change(data)){editing=null;counts=[0,0,0,0];setCounts();alert('復元しました')}}catch(err){alert('読み込みに失敗しました：'+err.message)}finally{e.target.value=''}};
setCounts();render();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
